---
bycon_definition_files:
  - config
  - argument_definitions
  - filter_definitions
  - dataset_definitions
  - interval_definitions
  - variant_definitions
  - datatable_mappings
defaults:
  genome_binning: 1Mb
  import_files_root:
    - imports


