---
bycon_definition_files:
  - config
  - filter_definitions
  - dataset_definitions
  - interval_definitions
  - handover_definitions
  - variant_definitions
  - remap_definitions
  - text_patterns
  - datatable_mappings
defaults:
  genome_binning: 1Mb
  import_files_root:
    - imports


